<?php
/*
$c = getCityContext();
if($c->field_promoted_city[LANGUAGE_NONE][0]['value'] == 0){
print '<div class="promote-your-city padded">'.
        '<span class="bg-diag">'.
            '<span class="center-bg banner" href="#" style="background-image: url(\'/sites/all/themes/liv/livability/images/cityscape.png\')">'.
                '<span>Do you live in '.$c->title.', '.$c->state->field_state_code['und'][0]['value'].
                    '?<a href="http://promote.livability.com/"> Learn how to promote your city!</a>
                </span>
            </span>
        </span>
        '.
    '</div>';
}
*/