<?php
/**
 * @file
 * Module file for footer_about_block.
 */

/**
 * @defgroup footer_about_block Footer About Block
 * @ingroup livability
 * @{
 * Creates a configuratble block for the footer.
 *
 */

/**
 * Implements hook_block_info().
 */
function footer_about_block_block_info() {
  $blocks['footer_about_text'] = array(
    // info: The name of the block.
    'info' => t('Footer About Text'),
    // Block caching options (per role, per user, etc.)
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function footer_about_block_block_configure($delta = '') {
  $form = array();
  if ($delta == 'footer_about_text') {
    $form['footer_about_block_string'] = array(
      '#type' => 'textarea',
      '#title' => t('About text'),
      '#description' => t('This text will appear in the Footer About Text block.'),
      '#default_value' => variable_get('footer_about_block_string',  t('')),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function footer_about_block_block_save($delta = '', $edit = array()) {
  if ($delta == 'footer_about_text') {
    variable_set('footer_about_block_string', $edit['footer_about_block_string']);
  }
  return;
}

/**
 * Implements hook_block_view().
 */
function footer_about_block_block_view($delta = '') {
  switch ($delta) {
    case 'footer_about_text':
//      $block['subject'] = variable_get('footer_about_block_title',  t('About'));
      $block['content'] = array('#markup' => variable_get('footer_about_block_string',  t('Whoops! No about text set.')));
      break;
  }
  return $block;
}

/**
 * @} End of "footer_about_block".
 */
