<?php
/**
 * @file
 * media_settings.features.filter.inc
 */

/**
 * Implements hook_filter_default_formats().
 */
function media_settings_filter_default_formats() {
  $formats = array();

  // Exported format: Photo Byline.
  $formats['photo_byline'] = array(
    'format' => 'photo_byline',
    'name' => 'Photo Byline',
    'cache' => 1,
    'status' => 1,
    'weight' => -7,
    'filters' => array(
      'filter_html' => array(
        'weight' => -10,
        'status' => 1,
        'settings' => array(
          'allowed_html' => '<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd>',
          'filter_html_help' => 1,
          'filter_html_nofollow' => 1,
        ),
      ),
      'filter_url' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(
          'filter_url_length' => 72,
        ),
      ),
      'filter_htmlcorrector' => array(
        'weight' => 10,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  return $formats;
}
