
<!-- DFP targeting Start -->
<script>
  googletag.cmd.push(function() {
    googletag.pubads().setTargeting('City', ['27740']);
    googletag.pubads().setTargeting('Category', ['liv_home']);
    googletag.pubads().setTargeting('Nid ', ['liv-56079']);
    googletag.pubads().setTargeting('Path', ['tn/franklin']);
    googletag.pubads().setTargeting('Type', ['city']);
    googletag.pubads().setTargeting('State', ['TN']);
    googletag.pubads().setTargeting('Project', ['LIV_306']);
    googletag.pubads().setTargeting('Project', ['LIV_306_all']);
    googletag.pubads().setTargeting('Project', ['LIV_306_home']);
    googletag.pubads().setTargeting('Page', ['city_home']);
    googletag.pubads().setTargeting('Project', ['Franklin/TN']);
    googletag.pubads().setTargeting('Project', ['LIV_151']);
    googletag.pubads().setTargeting('Project', ['LIV_151_all']);
    googletag.pubads().enableSyncRendering();
    googletag.enableServices();
  });
</script>
<!-- DFP targeting End -->
